# Generated by Django 4.2.7 on 2026-04-28 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('salary', models.CharField(blank=True, default='', max_length=100)),
                ('experience', models.CharField(blank=True, default='', max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicants_count', models.IntegerField(default=0)),
                ('blind_mode', models.BooleanField(default=False)),
                ('blind_mode_locked', models.BooleanField(default=False)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('is_skill_based', models.BooleanField(default=False)),
                ('min_match_threshold', models.IntegerField(default=70)),
                ('health_score', models.IntegerField(default=50)),
                ('tier', models.CharField(choices=[('promoted', 'Promoted'), ('standard', 'Standard'), ('high', 'High')], default='standard', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('tier_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
