# Generated by Django 4.2.7 on 2026-04-28 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('duration_days', models.IntegerField(default=3)),
                ('compensation', models.CharField(blank=True, default='', max_length=100)),
                ('max_candidates', models.IntegerField(default=5)),
                ('deliverable', models.TextField(blank=True, default='')),
                ('rubric', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.ManyToManyField(blank=True, related_name='internship_accepted', to=settings.AUTH_USER_MODEL)),
                ('applicants', models.ManyToManyField(blank=True, related_name='internship_applications', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'micro_internships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroInternshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_text', models.TextField(blank=True, default='')),
                ('deliverable_url', models.CharField(blank=True, default='', max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('evaluation', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('below_expectation', 'Below Expectation')], default='good', max_length=30)),
                ('recruiter_notes', models.TextField(blank=True, default='')),
                ('fast_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_submissions', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='marketplace.microinternship')),
            ],
            options={
                'db_table': 'micro_internship_submissions',
                'unique_together': {('internship', 'candidate')},
            },
        ),
    ]
