# Generated by Django 4.2.7 on 2026-04-28 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('examples', models.JSONField(default=list)),
                ('constraints', models.JSONField(default=list)),
                ('starter_code', models.JSONField(default=dict)),
                ('test_cases', models.JSONField(default=list)),
                ('optimal_solution', models.TextField(blank=True, default='')),
                ('time_complexity', models.CharField(blank=True, default='', max_length=50)),
                ('space_complexity', models.CharField(blank=True, default='', max_length=50)),
                ('xp', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coding_problems',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('company_logo', models.CharField(blank=True, default='', max_length=500)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('duration_hours', models.IntegerField(default=4)),
                ('reward', models.CharField(blank=True, default='', max_length=100)),
                ('tech_stack', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('starter_code_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('submissions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('today_xp', models.IntegerField(default=0)),
                ('last_reset_date', models.CharField(default='', max_length=10)),
                ('log', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_xp',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('daily_goal', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='ResumeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('job_url', models.CharField(blank=True, default='', max_length=500)),
                ('match_score', models.IntegerField(default=0)),
                ('ats_probability', models.IntegerField(default=0)),
                ('domain_overlap', models.IntegerField(default=0)),
                ('hard_skills_missing', models.JSONField(default=list)),
                ('soft_skills_missing', models.JSONField(default=list)),
                ('experience_delta', models.CharField(blank=True, default='', max_length=255)),
                ('keyword_matches', models.JSONField(default=list)),
                ('keyword_missing', models.JSONField(default=list)),
                ('resume_suggestions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('tier', models.CharField(default='Bronze', max_length=20)),
                ('percentile', models.IntegerField(default=50)),
                ('signals', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('github_connected', models.BooleanField(default=False)),
                ('github_username', models.CharField(blank=True, default='', max_length=100)),
                ('leetcode_connected', models.BooleanField(default=False)),
                ('leetcode_username', models.CharField(blank=True, default='', max_length=100)),
                ('employer_endorsements', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_scores',
            },
        ),
        migrations.CreateModel(
            name='ReadinessScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('dimensions', models.JSONField(default=list)),
                ('badge', models.CharField(default='Bronze', max_length=20)),
                ('percentile', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'readiness_scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, default='')),
                ('repo_url', models.CharField(blank=True, default='', max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='features.project')),
            ],
            options={
                'db_table': 'project_submissions',
            },
        ),
        migrations.CreateModel(
            name='PeerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='JavaScript', max_length=50)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('participants', models.JSONField(default=list)),
                ('chat_log', models.JSONField(default=list)),
                ('ratings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_rooms_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peer_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('hr', 'HR'), ('technical', 'Technical')], max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('input_mode', models.CharField(default='text', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('questions', models.JSONField(default=list)),
                ('overall_score', models.FloatField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=255)),
                ('total_days', models.IntegerField(default=60)),
                ('current_day', models.IntegerField(default=1)),
                ('estimated_ready_date', models.CharField(blank=True, default='', max_length=100)),
                ('is_fast_track', models.BooleanField(default=False)),
                ('weeks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_paths',
            },
        ),
        migrations.CreateModel(
            name='InterviewRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('invitee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('recording_url', models.CharField(blank=True, default='', max_length=500)),
                ('recording_consent', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0)),
                ('post_session_report', models.JSONField(blank=True, default=dict)),
                ('chat_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(default='Software Engineer', max_length=255)),
                ('timeline', models.CharField(default='3 months', max_length=100)),
                ('company_tier', models.CharField(default='Any', max_length=100)),
                ('target_company', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'copilot_goals',
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit'), ('error', 'Error')], default='wrong_answer', max_length=20)),
                ('runtime', models.CharField(blank=True, default='', max_length=50)),
                ('memory', models.CharField(blank=True, default='', max_length=50)),
                ('xp_earned', models.IntegerField(default=0)),
                ('test_results', models.JSONField(default=list)),
                ('quality_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='features.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coding_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeQualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('overall_score', models.IntegerField(default=0)),
                ('readability', models.IntegerField(default=0)),
                ('maintainability', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('security', models.IntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_quality_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'code_quality_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
    ]
